### ISSUE TITLE
Need some way to uninstall/reinstall the driver

### ISSUE THREAD

**Issue by nnadtoka** [facebookarchive/presto-odbc#42]
First of all, thanks for your good work!

Is there any simple way to uninstall/reinstall the presto odbc driver? For some reason changing the user to another one on the same windows machine and trying to use Tableau and presto odbc driver (install was for all users) messed up the connection to the driver from Tableau for all users. A quick fix I can think of was to re-install the driver. Any ideas how to do it?

I have tried using it from another machine with a new presto odbc driver installation and it went just fine. 

Thanks!
Nat.

**Comment by nezihyigitbasi** [comment]
I recently created a PR (#41) for a graphical installer for Windows, which also creates an uninstaller when you install the driver with that. That's one way to do it. The other way is to manually delete the relevant keys from registry and re-run the registry script. 

BTW to understand what is really going on it always helps to look at the logs.

**Comment by nnadtoka** [comment]
Thanks for a quick reply. You are absolutely right, logs can be useful to pinpoint the issue. I will try to provide them another time.

I have a quick question. Actually two questions.
1. I've seen that most of things are about 64 bits version of Windows. Will the driver work on 32 bits configuration?
2. Do you see any limitations with Windows virtual machine use case scenario?

**Comment by nezihyigitbasi** [comment]
Currently the driver doesn't have a 32 bit version, but I am currently trying to create a 32 bit version to use the driver with some other tool. I am having some problems with that btw, so please feel free to contribute if you plan to work on that.

I have been using the driver on EC2 windows instances and I haven't experienced any significant limitations so far.

**Comment by nnadtoka** [comment]
Thanks for trying to make it work with 32 bit version. It'll be very handy. I am not a dev myself, but let me see if anyone on our team is willing to contribute.

Interestingly enough, I resolved my issue (presto odbc with Tableau working for one user, then not working for anyone at all on that machine) by removing some giant presto_odbc file (got to 4Gb) that was stored in c:\temp 
I could then connect to presto with odbc driver from Tableau perfectly well. The file that I have created was recreated. I'll keep an eye on it. I wonder if that was some issue with this file getting too large.

**Comment by electrum** [comment]
It might be a permission issue. Using C:\temp was a hack for development to make it easier to find the logs. We should use the proper per-user temporary directory. There is a windows call to get it, though D night already have a wrapper (which we'll need for cross platform).

**Comment by andralex** [comment]
For fetching the temp dir location, check http://dlang.org/phobos/std_file.html#.tempDir
